### ISSUE TITLE
Demo stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#116]
the demo stage is already amazing! if possible, here are things to be done by the end of this week (this list is not in order of importance - just do the ones that are possible; everything is a bonus for us!):

- [x] audience view of stage: it would be nice to be able to show the audience view of the stage, that is not logged in at all, no visible tools or access to tools, so that we can see how it will look at audiences
- [x] backdrops: in UpStage v3, the backdrop fills the browser window and doesn't tile; can that be done in the demo stage?
- [x] arrangement of visual assets: we need to be able to move avatars & props in front of and behind each other (tool should be in the context menu)
- [x] - [ ] change nickname in context menu (#114 )
- [x] flip & rotate avatar (#56)
- [x] avatar animation: possibility to make a muti-frame avatar cycle through its frames (i.e. aniamte) (#37 )
- [x] speed adjustment - so that avatar moves quickly or slowly across stage; also in context menu
- [x] this might be more complex than what is achieveable by friday, but "costume props" or a way to fake this would be great (see wireframes on #64 also #58 ).

**Comment by helenvarley** [comment]
there is an issue when an avatar is near to the chat window, and the context menu disappears under the chat window so that you can't access all of the animation options. for the demo, i can be aware of this & keep the avatars away from the chat, but in the longer term this needs to be addressed.

**Comment by nguyenhongphat0** [comment]
The context menu position need to be improving. I think I will pop it to the top left so that when an avatar is at the bottom of the stage, you can still use it context menu

**Comment by helenvarley** [comment]
@nguyenhongphat0 please have a look at the wireframes, also @elisadcg please have a look at the context menu on the demo stage :)

**Comment by elisadcg** [comment]
top left of the screen or top left of the avatar ? 
The problem is the chat window. But we had think that the position of the chat window could change (on the left or on the right).
Maybe the best is to put the context menu above the chat ?

**Comment by nguyenhongphat0** [comment]
![image](https://user-images.githubusercontent.com/29925961/104324268-ce61ee80-5519-11eb-8cff-a6d4c7d89b4f.png)
Hmm I think we will have 2 context menu. One above of the avatar like the wireframe above. And the other is sub context menu, like the one we're having right now. Right, Elisa?

**Comment by nguyenhongphat0** [comment]
> top left of the screen or top left of the avatar ?
> The problem is the chat window. But we had think that the position of the chat window could change (on the left or on the right).
> Maybe the best is to put the context menu above the chat ?
Top left of the avatar, like this:
![image](https://user-images.githubusercontent.com/29925961/104325121-d53d3100-551a-11eb-8954-16f99931d75c.png)

**Comment by elisadcg** [comment]
Phat, the first you posted is the context menu during the cyberformance.
And the second one is the overlay during the preparation of the futur stage.
But i remember Gloria said : it could be the same !
So if this big overlay is not disturbing the performance, we can let it. And yes workaround is good : always be away from the window chat.

**Comment by helenvarley** [comment]
yes we have a lot to get into these context menus!! i think there are some important points to be aware of:
- the workshop overlay is a different thing, & i don't think it can be the same as the menu that you need for performances; in performance you often need to be able to do things quickly, and having too many options in a menu slows you down. so it's better to keep the performance tools in one menu, and the workshop overlay separate
- the second image phat posted here is actually the performance tools context menu in the demo stage, not the workshop overlay. it looks similar, because it contains thumbnails of all the frames in an animated avatar. it could be that we need to find another way to have the avatar animation ... because at the moment it is taking up a lot of space in the context menu.
- lastly, the context menu will probably have to be moveable: it might be that the avatar is close to the chat, & yes the idea is that people can choose to have the chat window on the left or the right. it can also be that the avatar is close to the top or the bottom of the stage, and some of the context menu disappears off the top or the bottom. so the menu needs to be able to adjust so that it is always visible. (in the old UpStage, this happened with speech bubbles - if your avatar was near the top of the screen, the speech bubble would appear below the avatar so that is was still visible)

so ... overall i think we need to be as economical as possible in the context menu, and look for design ideas to make it compact as well as being clever about how many items we really need ...  this can be worked on further after the presentations with the demo stage. the demo stage is very helpful for allowing us to really see & think about all these things :)

**Comment by nguyenhongphat0** [comment]
The first four checklist is done and deployed at http://159.89.19.111/V4.0/ui/live. You can visit it and try open it in incognito tab to see the audience view (which is just a stage with a chatbox), and then login the see the player view.

**Comment by nguyenhongphat0** [comment]
About "flip & rotate avatar (#56)"
Since I'm using a library for dragging/resizing things. To save the efforts, I'm asking for the author of that library for the rotating and waiting for his reply (https://github.com/a7650/vue3-draggable-resizable/issues/9). If he didn't consider it then I I'll do it myself :sweat_smile:

**Comment by helenvarley** [comment]
at the log-in for the demo stage, there is the option to enter username & password, and underneath "login as guest" to enter audience view. 
could this be changed to say "enter as guest" rather than log in?  guests don't actually log in, they just enter.

**Comment by nguyenhongphat0** [comment]
You got it :+1: 
![image](https://user-images.githubusercontent.com/29925961/104614952-52071100-56bb-11eb-927e-b9393dac9ec8.png)

**Comment by helenvarley** [comment]
this is going to come up as an issue of its own for sure, but i have noticed discrepancies in positions of asssets on the stage - one of the developer's favourite challenges as i'm sure paul will tell you ;)
here are screen shots of the player view (in firefox) and the audience view (in chromium). nearly everything is in the right place, except for one of the avatars.
fixing this is NOT a priority for the demo stage, i'm just posting it here now to flag it up as it will be an issue down the track. getting things as near the same as possible for everyone is pretty crucial.
![Screenshot at 2021-01-14 17-10-23](https://user-images.githubusercontent.com/3437324/104617517-d17cec00-568b-11eb-920b-035877b2160c.png)
![Screenshot at 2021-01-14 17-10-32](https://user-images.githubusercontent.com/3437324/104617582-e5285280-568b-11eb-83c7-639c21cbad17.png)

**Comment by nguyenhongphat0** [comment]
As suggestion of Gloria, now when you put a prop in place of an avatar, that prop is attached to that avatar, so when the avatar move the prop will move along

About the flip and rotation, the best thing I can do now is provide a +45deg and -45deg button in the context menu, so when you click it the avatar/prop rotate a bit. Take a look:
<img src="https://user-images.githubusercontent.com/29925961/104810102-361f7e80-5825-11eb-85a2-8211007a0a81.png" width="300"> <img src="https://user-images.githubusercontent.com/29925961/104810172-9adad900-5825-11eb-96ae-6abe682c1225.png" width="300">

As soon as the library support I will add a "rotate button", like this:
<img src="https://user-images.githubusercontent.com/29925961/104403165-80390380-558a-11eb-961c-1e6832abc248.png" width="300">

**Comment by nguyenhongphat0** [comment]
> this is going to come up as an issue of its own for sure, but i have noticed discrepancies in positions of asssets on the stage - one of the developer's favourite challenges as i'm sure paul will tell you ;)

About the discrepancies in positions, I don't know exactly what reason cause it, but I did some improvements in the way an avatar/prop receive new move command when it's already moving. Hope the bug is gone with it :sweat_smile:

**Comment by helenvarley** [comment]
> As suggestion of Gloria, now when you put a prop in place of an avatar, that prop is attached to that avatar, so when the avatar move the prop will move along
> 
actually this is not good, because it means that you end up with props attached to avs when you don't want them to be ...
